function ddthetalist = ForwardDynamics(thetalist, dthetalist, taulist, ...
                                       g, Ftip, Mlist, Glist, Slist)
ddthetalist = MassMatrix(thetalist, Mlist, Glist, Slist) ...
              \ (taulist - VelQuadraticForces(thetalist, dthetalist, ...
                                              Mlist, Glist, Slist) ...
                 - GravityForces(thetalist, g, Mlist, Glist, Slist) ...
                 - EndEffectorForces(thetalist, Ftip, Mlist, Glist, ...
                                     Slist));
end